packages:
  - '.vscode/extensions/*'
  - './app'
  - './pkgs/siyuan/app'
  - './docs/starlight'
  - '../sofillBuilder'
  # exclude packages that are inside test directories
  - '!**/test/**'

# Default catalogs
catalog:
  typescript: ^5.5.2
  react: 18.3.1
  react-dom: 18.3.1
  electron: 31.1.0
  electron-builder: 24.9.1
  date-fns: ^3.6.0
  sofill: ^1.1.10
