import os,sys,time
import subprocess
root = os.path.dirname(os.path.dirname(__file__))
app = os.path.join(root, 'app')
kernel = os.path.join(app, 'kernel')
print(app)
os.system('taskkill /f /t /im SiYuan-Kernel.exe')
# b = subprocess.Popen('call SiYuan-Kernel.exe --wd=.. --mode=dev', shell=True, cwd=kernel, env=os.environ,creationflags =subprocess.CREATE_NEW_CONSOLE)
p1 = subprocess.Popen('cmd', shell=True, cwd=kernel, env=os.environ, creationflags=subprocess.CREATE_NEW_CONSOLE, stdin=subprocess.PIPE)
p1.stdin.write(('%s\n' % 'call SiYuan-Kernel.exe --wd=.. --mode=dev').encode('utf-8'))
time.sleep(1000)
# p = subprocess.Popen('pnpm run start', shell=True, cwd=app, env=os.environ,creationflags =subprocess.CREATE_NEW_CONSOLE)
p2 = subprocess.Popen('cmd', shell=True, cwd=app, env=os.environ, creationflags=subprocess.CREATE_NEW_CONSOLE, stdin=subprocess.PIPE)
p2.stdin.write(('%s\n' % 'pnpm run start').encode('utf-8'))
time.sleep(1000)
a = subprocess.Popen('start http://localhost:6806', shell=True, cwd=app, env=os.environ)
a.wait()
p1.wait()
p2.wait()