on:
  workflow_run:
      workflows: ["Sillot CI/CD"]
      types:
        - completed
  # release:
  #   types: [published]
    # https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#release
jobs:
  genHASH:
    name: Create hash for release
    runs-on: ubuntu-latest
    steps:
      - uses: MCJack123/ghaction-generate-release-hashes@v3
        with:
          hash-type: md5
          file-name: hashes-md5.txt
          get-assets: true # This is useful if previous jobs in a workflow upload assets, as GitHub's list will not include them
      - uses: actions/upload-artifact@v2
        with:
          name: Asset Hashes
          path: hashes-md5.txt
