name: Nightly

on:
  schedule:
    # Run every Monday at 12:00 UTC
    - cron: "0 12 * * 1"
  workflow_dispatch:

jobs:
  lockfile:
    if: github.repository_owner == 'withastro'
    uses: withastro/automation/.github/workflows/lockfile.yml@main
    secrets: inherit
