name: PR check

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v2
        env:
          # secrets.GITHUB_TOKEN 是 Github 机器人的，这里的场景不用机器人会很怪异
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: master | dev
          exclude: master-dev | master | dev
          change-to: master-dev
          comment: |
            PRs should be target `master-dev`
            The base branch of this PR has been automatically changed to `master-dev`
            Please check that there are no merge conflicts
