name: Make sure new PRs are sent to master-dev

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
        with:
          target: dev
          exclude: master-dev
          change-to: master-dev
          comment: |
            Your PR was set to target `dev`, PRs should be target `master-dev`
            The base branch of this PR has been automatically changed to `master-dev`, please check that there are no merge conflicts
